spring:
 cloud:
   gateway:
     discovery.locator: 
       enabled: true
       lowerCaseServiceId: true

server:
  port: 8072
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER:localhost}:8070/eureka/
