spring:
  cloud:
    stream:
      bindings:
        publish-out-0:
          destination: publisher_channel
        subscribe-in-0:
          destination: subscriber_channel
        process-in-0:
          destination: publisher_channel
        process-out-0:
          destination: subscriber_channel
      kafka:
        binder:
          zkNodes: localhost
          brokers: localhost




server:
  port: 8081
  
redis:
  server:
    host: localhost
    port: 6379
  
eureka:
 instance:
   preferIpAddress: true
 client:
   registerWithEureka: true
   fetchRegistry: true
   should-unregister-on-shutdown: true
   serviceUrl: 
     defaultZone: http://${EUREKA_SERVER:localhost}:8070/eureka/  

management:
  health:
    circuitbreakers:
      enabled: true
  endpoint:
    health:
      show-details: 'always'
      
  endpoints:
    web:
      base-path: /managment
      exposure:
        include: health,info,beans,conditions,env,refresh
        #exclude: health,info,beans,conditions,env
        
resilience4j:
  circuitbreaker:
    instances:
      course-adapter: 
        registerHealthIndicator: true   
        ringBufferSizeInClosedState: 5   
        ringBufferSizeInHalfOpenState: 3 
        waitDurationInOpenState: 60s
        failureRateThreshold: 50 
     
#from project
#spring:
#  cloud:
#    circuitbreaker:
#      resilience4j:
#        enabled: true



#resilience4j:
#  circuitbreaker:
#    configs:
#      shared:
#        sliding-window-type: count_based
#        sliding-window-size: 3
#        failure-rate-threshold: 50
#    instances:
#      licenseService:
#        base-config: shared     
